version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: shulikin/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: shulikin/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  # gateway:
  #   image: shulikin/foodgram_nginx
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - static:/static
  #     - media:/media
  #   depends_on:
  #     - frontend
  #     - backend


  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend