# Generated by Django 3.2.3 on 2024-10-05 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20241005_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1, 'Не может быть меньше 1 мин.')], verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
